# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    #  args:
    #    ARG: <ARG>
    image: ift6758/serving:latest
    ports:
      - 8000:8000
    environment:
      WANDB_API_KEY: ${WANDB_API_KEY}
  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
      # args:
      #   ARG: <ARG>
    image: ift6758/streamlit:latest
    ports:
      - 8001:8001