_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 5
                - 6
                - 35
                - 53
                - 55
            "2":
                - 5
                - 6
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.18.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
cv_folds:
    value: 3
eval_metric:
    value: logloss
model:
    value: XGBClassifier
